# Generated by Django 6.0.1 on 2026-01-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronostics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronostic',
            name='score_domicile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='score_exterieur',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
