# Generated by Django 6.0.1 on 2026-01-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronostics', '0002_alter_pronostic_score_domicile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='journee',
            field=models.IntegerField(default=1),
        ),
    ]
