# Generated by Django 6.0.1 on 2026-01-19 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronostics', '0003_match_journee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='equipe_domicile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_domicile', to='pronostics.equipe'),
        ),
        migrations.AlterField(
            model_name='match',
            name='equipe_exterieure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_exterieure', to='pronostics.equipe'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='saison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pronostics.saison'),
        ),
        migrations.AlterUniqueTogether(
            name='equipe',
            unique_together={('nom', 'saison')},
        ),
    ]
