# Generated by Django 6.0.1 on 2026-01-19 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronostics', '0004_equipe_saison_alter_match_equipe_domicile_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipe',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='equipe',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='match',
            name='saison',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pronostics.saison'),
        ),
        migrations.AddField(
            model_name='saison',
            name='equipes',
            field=models.ManyToManyField(related_name='saisons', to='pronostics.equipe'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='saison',
        ),
    ]
